name: build
on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Generate signing key
        run: pacman-key --init
      - name: Update distribution packages
        run: pacman -Syu --noconfirm
      - name: Check running environment
        run: pacman -S --noconfirm neofetch && neofetch
