name: build
on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      volumes:
        - data:/data
    steps:
      - uses: actions/checkout@v3
      - name: Generate signing key
        run: pacman-key --init
      - name: Update distribution packages
        run: pacman -Syu --noconfirm
      - name: Create build user
        run: |
          pacman -S --needed --noconfirm git sudo
          useradd builder -m
          passwd -d builder
          printf '\nbuilder ALL=(ALL) ALL\n' | tee -a /etc/sudoers
          chown -R builder:builder /data
      - name: Clone and build packages
        run: |
          sudo -u builder bash -c "cd /data && git clone https://github.com/rocm-arch/rocm-arch.git"
          sudo -u builder bash -c "cd /data/rocm-arch/rocm-llvm && makepkg -s --noconfirm"
