name: build
on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/cache@v3
      #   with:
      #     key: pacman-cache
      #     path: ${{ github.workspace }}
      - name: Setup build environment
        run: bash setup.sh

      - name: Build rocm-llvm
        run: |
          sudo -u builder bash -c "cd pkgs && git clone https://aur.archlinux.org/rocm-llvm.git && cd rocm-llvm && makepkg -s --noconfirm"

      # - name: Clone and build packages
      #   run: |
      #     sudo -u builder bash -c "cd /data && git clone https://github.com/rocm-arch/rocm-arch.git"
      #     sudo -u builder bash -c "cd /data/rocm-arch/rocm-llvm && makepkg -s --noconfirm"
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/**/*.pkg.tar.zst
